[package]
name = "lazyreq"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A lazy, file-based HTTP client for your terminal"
repository = "https://github.com/2yuri/lazyreq"

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json", "multipart"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.3", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
async-recursion = "1.1.1"
colored = "2.0"
home = "0.5"
mime_guess = "2.0"
rand = "0.8"
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
base64 = "0.22"
hex = "0.4"
